# Generated by Django 3.0.7 on 2020-07-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('crm', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.TimeField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Agenda')),
            ],
            options={
                'ordering': ['horarios'],
                'unique_together': {('horarios', 'agenda')},
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('data_agendamento', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Horarios')),
                ('medico', models.ManyToManyField(to='app.Medico')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Medico'),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
    ]
