# Generated by Django 3.0.7 on 2020-07-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia', 'horario')},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='data_agendamento',
        ),
    ]
