# Generated by Django 3.0.7 on 2020-07-24 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 1, 4, 41, 822723, tzinfo=utc), editable=False),
        ),
    ]
