# Generated by Django 3.0.7 on 2020-07-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(),
        ),
    ]
