# Generated by Django 3.0.7 on 2020-07-24 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200724_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 1, 5, 4, 988844, tzinfo=utc), editable=False),
        ),
    ]
