# Generated by Django 3.0.7 on 2020-07-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200722_0027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medico',
            table=None,
        ),
    ]
