# Generated by Django 3.0.7 on 2020-07-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200724_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horario',
            new_name='horarios',
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia', 'horarios')},
        ),
    ]
