# Generated by Django 3.0.7 on 2020-07-24 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200724_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 1, 30, 25, 669116, tzinfo=utc), editable=False),
        ),
    ]
