# Generated by Django 3.0.7 on 2020-07-22 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200722_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(9999999999), django.core.validators.MinLengthValidator(1000)]),
        ),
    ]
