# Generated by Django 3.0.7 on 2020-07-24 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200724_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 2, 15, 23, 15635, tzinfo=utc), editable=False),
        ),
    ]
