# Generated by Django 3.0.7 on 2020-07-24 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200724_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia']},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 2, 36, 35, 239033, tzinfo=utc), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('dia', 'horario', 'medico')},
        ),
    ]
